# Generated by Django 3.0.6 on 2020-05-29 17:11

import Dostawa_Domain.Model.DeliveryType.DeliveryType
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_NameField', models.CharField(max_length=200)),
                ('_PriceField', models.PositiveIntegerField()),
                ('_DeliveryTimeField', models.CharField(max_length=200)),
            ],
            bases=(models.Model, Dostawa_Domain.Model.DeliveryType.DeliveryType.DeliveryType),
        ),
    ]
