# Generated by Django 3.0.6 on 2020-05-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dostawa_Infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='_PackageCodeField',
            field=models.BigIntegerField(),
        ),
    ]
