# Generated by Django 2.0.7 on 2019-12-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wydarzenie',
            options={'verbose_name': 'wydarzenie', 'verbose_name_plural': 'wydarzenia'},
        ),
    ]
