# Generated by Django 2.0.7 on 2019-12-11 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarz', '0002_auto_20191211_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.TextField(max_length='50')),
                ('nazwisko', models.TextField(max_length='50')),
                ('email', models.TextField(max_length='50')),
            ],
            options={
                'verbose_name': 'osoba',
                'verbose_name_plural': 'osoby',
            },
        ),
        migrations.RemoveField(
            model_name='wydarzenie',
            name='godz',
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='data_wydarzenia',
            field=models.DateField(default=datetime.date(2019, 12, 11)),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='godz_rozpoczecia',
            field=models.TimeField(default=datetime.datetime(2019, 12, 11, 14, 49, 48, 891677)),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='godz_zakonczenia',
            field=models.TimeField(default=datetime.datetime(2019, 12, 11, 14, 49, 48, 891693)),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='opis',
            field=models.TextField(blank=True, max_length='500', null=True),
        ),
    ]
