# Generated by Django 2.0.7 on 2019-12-11 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kalendarz', '0006_auto_20191211_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydarzenie',
            name='uczestnicy',
            field=models.ManyToManyField(to='kalendarz.Osoba'),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='data_wydarzenia',
            field=models.DateField(default=datetime.datetime(2019, 12, 11, 15, 26, 59, 392325, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='godz_rozpoczecia',
            field=models.TimeField(default=datetime.datetime(2019, 12, 11, 15, 26, 59, 392345, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='godz_zakonczenia',
            field=models.TimeField(default=datetime.datetime(2019, 12, 11, 15, 26, 59, 392359, tzinfo=utc)),
        ),
    ]
